# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/filer358/tdp005

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/filer358/tdp005

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filer358/tdp005/CMakeFiles /home/filer358/tdp005/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filer358/tdp005/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bubble

# Build rule for target.
bubble: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bubble
.PHONY : bubble

# fast build rule for target.
bubble/fast:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/build
.PHONY : bubble/fast

# target to build an object file
source/main.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/main.o
.PHONY : source/main.o

# target to preprocess a source file
source/main.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/main.i
.PHONY : source/main.i

# target to generate assembly for a file
source/main.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/main.s
.PHONY : source/main.s

# target to build an object file
source/objects/imps/Drop.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop.o
.PHONY : source/objects/imps/Drop.o

# target to preprocess a source file
source/objects/imps/Drop.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop.i
.PHONY : source/objects/imps/Drop.i

# target to generate assembly for a file
source/objects/imps/Drop.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop.s
.PHONY : source/objects/imps/Drop.s

# target to build an object file
source/objects/imps/Drop_Behaviour_heart.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop_Behaviour_heart.o
.PHONY : source/objects/imps/Drop_Behaviour_heart.o

# target to preprocess a source file
source/objects/imps/Drop_Behaviour_heart.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop_Behaviour_heart.i
.PHONY : source/objects/imps/Drop_Behaviour_heart.i

# target to generate assembly for a file
source/objects/imps/Drop_Behaviour_heart.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop_Behaviour_heart.s
.PHONY : source/objects/imps/Drop_Behaviour_heart.s

# target to build an object file
source/objects/imps/Drop_Behaviour_points.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop_Behaviour_points.o
.PHONY : source/objects/imps/Drop_Behaviour_points.o

# target to preprocess a source file
source/objects/imps/Drop_Behaviour_points.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop_Behaviour_points.i
.PHONY : source/objects/imps/Drop_Behaviour_points.i

# target to generate assembly for a file
source/objects/imps/Drop_Behaviour_points.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Drop_Behaviour_points.s
.PHONY : source/objects/imps/Drop_Behaviour_points.s

# target to build an object file
source/objects/imps/Enemy.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Enemy.o
.PHONY : source/objects/imps/Enemy.o

# target to preprocess a source file
source/objects/imps/Enemy.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Enemy.i
.PHONY : source/objects/imps/Enemy.i

# target to generate assembly for a file
source/objects/imps/Enemy.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Enemy.s
.PHONY : source/objects/imps/Enemy.s

# target to build an object file
source/objects/imps/Enemy_Behaviour.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Enemy_Behaviour.o
.PHONY : source/objects/imps/Enemy_Behaviour.o

# target to preprocess a source file
source/objects/imps/Enemy_Behaviour.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Enemy_Behaviour.i
.PHONY : source/objects/imps/Enemy_Behaviour.i

# target to generate assembly for a file
source/objects/imps/Enemy_Behaviour.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Enemy_Behaviour.s
.PHONY : source/objects/imps/Enemy_Behaviour.s

# target to build an object file
source/objects/imps/Game.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Game.o
.PHONY : source/objects/imps/Game.o

# target to preprocess a source file
source/objects/imps/Game.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Game.i
.PHONY : source/objects/imps/Game.i

# target to generate assembly for a file
source/objects/imps/Game.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Game.s
.PHONY : source/objects/imps/Game.s

# target to build an object file
source/objects/imps/Key_Handling.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Key_Handling.o
.PHONY : source/objects/imps/Key_Handling.o

# target to preprocess a source file
source/objects/imps/Key_Handling.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Key_Handling.i
.PHONY : source/objects/imps/Key_Handling.i

# target to generate assembly for a file
source/objects/imps/Key_Handling.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Key_Handling.s
.PHONY : source/objects/imps/Key_Handling.s

# target to build an object file
source/objects/imps/Level.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Level.o
.PHONY : source/objects/imps/Level.o

# target to preprocess a source file
source/objects/imps/Level.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Level.i
.PHONY : source/objects/imps/Level.i

# target to generate assembly for a file
source/objects/imps/Level.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Level.s
.PHONY : source/objects/imps/Level.s

# target to build an object file
source/objects/imps/Menu.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Menu.o
.PHONY : source/objects/imps/Menu.o

# target to preprocess a source file
source/objects/imps/Menu.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Menu.i
.PHONY : source/objects/imps/Menu.i

# target to generate assembly for a file
source/objects/imps/Menu.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Menu.s
.PHONY : source/objects/imps/Menu.s

# target to build an object file
source/objects/imps/Platform.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Platform.o
.PHONY : source/objects/imps/Platform.o

# target to preprocess a source file
source/objects/imps/Platform.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Platform.i
.PHONY : source/objects/imps/Platform.i

# target to generate assembly for a file
source/objects/imps/Platform.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Platform.s
.PHONY : source/objects/imps/Platform.s

# target to build an object file
source/objects/imps/Player.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Player.o
.PHONY : source/objects/imps/Player.o

# target to preprocess a source file
source/objects/imps/Player.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Player.i
.PHONY : source/objects/imps/Player.i

# target to generate assembly for a file
source/objects/imps/Player.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Player.s
.PHONY : source/objects/imps/Player.s

# target to build an object file
source/objects/imps/Player1_Behaviour.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Player1_Behaviour.o
.PHONY : source/objects/imps/Player1_Behaviour.o

# target to preprocess a source file
source/objects/imps/Player1_Behaviour.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Player1_Behaviour.i
.PHONY : source/objects/imps/Player1_Behaviour.i

# target to generate assembly for a file
source/objects/imps/Player1_Behaviour.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Player1_Behaviour.s
.PHONY : source/objects/imps/Player1_Behaviour.s

# target to build an object file
source/objects/imps/Projectile.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Projectile.o
.PHONY : source/objects/imps/Projectile.o

# target to preprocess a source file
source/objects/imps/Projectile.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Projectile.i
.PHONY : source/objects/imps/Projectile.i

# target to generate assembly for a file
source/objects/imps/Projectile.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Projectile.s
.PHONY : source/objects/imps/Projectile.s

# target to build an object file
source/objects/imps/Projectile_Behaviour.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Projectile_Behaviour.o
.PHONY : source/objects/imps/Projectile_Behaviour.o

# target to preprocess a source file
source/objects/imps/Projectile_Behaviour.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Projectile_Behaviour.i
.PHONY : source/objects/imps/Projectile_Behaviour.i

# target to generate assembly for a file
source/objects/imps/Projectile_Behaviour.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Projectile_Behaviour.s
.PHONY : source/objects/imps/Projectile_Behaviour.s

# target to build an object file
source/objects/imps/Texture_Container.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Texture_Container.o
.PHONY : source/objects/imps/Texture_Container.o

# target to preprocess a source file
source/objects/imps/Texture_Container.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Texture_Container.i
.PHONY : source/objects/imps/Texture_Container.i

# target to generate assembly for a file
source/objects/imps/Texture_Container.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/Texture_Container.s
.PHONY : source/objects/imps/Texture_Container.s

# target to build an object file
source/objects/imps/World.o:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/World.o
.PHONY : source/objects/imps/World.o

# target to preprocess a source file
source/objects/imps/World.i:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/World.i
.PHONY : source/objects/imps/World.i

# target to generate assembly for a file
source/objects/imps/World.s:
	$(MAKE) -f CMakeFiles/bubble.dir/build.make CMakeFiles/bubble.dir/source/objects/imps/World.s
.PHONY : source/objects/imps/World.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... bubble"
	@echo "... rebuild_cache"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/objects/imps/Drop.o"
	@echo "... source/objects/imps/Drop.i"
	@echo "... source/objects/imps/Drop.s"
	@echo "... source/objects/imps/Drop_Behaviour_heart.o"
	@echo "... source/objects/imps/Drop_Behaviour_heart.i"
	@echo "... source/objects/imps/Drop_Behaviour_heart.s"
	@echo "... source/objects/imps/Drop_Behaviour_points.o"
	@echo "... source/objects/imps/Drop_Behaviour_points.i"
	@echo "... source/objects/imps/Drop_Behaviour_points.s"
	@echo "... source/objects/imps/Enemy.o"
	@echo "... source/objects/imps/Enemy.i"
	@echo "... source/objects/imps/Enemy.s"
	@echo "... source/objects/imps/Enemy_Behaviour.o"
	@echo "... source/objects/imps/Enemy_Behaviour.i"
	@echo "... source/objects/imps/Enemy_Behaviour.s"
	@echo "... source/objects/imps/Game.o"
	@echo "... source/objects/imps/Game.i"
	@echo "... source/objects/imps/Game.s"
	@echo "... source/objects/imps/Key_Handling.o"
	@echo "... source/objects/imps/Key_Handling.i"
	@echo "... source/objects/imps/Key_Handling.s"
	@echo "... source/objects/imps/Level.o"
	@echo "... source/objects/imps/Level.i"
	@echo "... source/objects/imps/Level.s"
	@echo "... source/objects/imps/Menu.o"
	@echo "... source/objects/imps/Menu.i"
	@echo "... source/objects/imps/Menu.s"
	@echo "... source/objects/imps/Platform.o"
	@echo "... source/objects/imps/Platform.i"
	@echo "... source/objects/imps/Platform.s"
	@echo "... source/objects/imps/Player.o"
	@echo "... source/objects/imps/Player.i"
	@echo "... source/objects/imps/Player.s"
	@echo "... source/objects/imps/Player1_Behaviour.o"
	@echo "... source/objects/imps/Player1_Behaviour.i"
	@echo "... source/objects/imps/Player1_Behaviour.s"
	@echo "... source/objects/imps/Projectile.o"
	@echo "... source/objects/imps/Projectile.i"
	@echo "... source/objects/imps/Projectile.s"
	@echo "... source/objects/imps/Projectile_Behaviour.o"
	@echo "... source/objects/imps/Projectile_Behaviour.i"
	@echo "... source/objects/imps/Projectile_Behaviour.s"
	@echo "... source/objects/imps/Texture_Container.o"
	@echo "... source/objects/imps/Texture_Container.i"
	@echo "... source/objects/imps/Texture_Container.s"
	@echo "... source/objects/imps/World.o"
	@echo "... source/objects/imps/World.i"
	@echo "... source/objects/imps/World.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

